### ISSUE TITLE
system shortcuts in file paths not allowed

### ISSUE THREAD

**Issue by danielboscia** [appgate/sdpctl#243]
This may be considered a feature request more than an issue.

When referencing a file path via system shortcuts, ie \~/downloads  the shortcut is not recognized 

(base)user@M1-Maximus Documents % sdpctl configure --pem=\~/downlaods/Appgate_SDP_ctrl.domain.com_CA.pem
? Enter the url for the controller API (example https://appgate.controller.com/admin) https://ctrl.domain.com:8443/admin
1 error occurred:
        * File not found: /Users/user/Documents/\~/downlaods/Appgate_SDP_ctrl.domain.com_CA.pem

(base) user@M1-Maximus Documents % cd \~/downloads
(base) user@M1-Maximus downloads % sdpctl configure --pem=Appgate_SDP_ctrl.domain.com_CA.pem 
? Enter the url for the controller API (example https://appgate.controller.com/admin) https://ctrl.domain.com:8443/admin
Configuration updated successfully
(base) user@M1-Maximus downloads %

**Comment by kajes** [comment]
Thank you for the report!

I can reproduce it, so definitely a bug.
```bash
# This does not work:
>sdpctl configure --pem=~/Downloads/pem.pem

# Replacing '=' with a space works:
>sdpctl configure --pem ~/Downloads/pem.pem
```
